//liking the post or unliking
export const LIKE_UPLOAD_REQUEST = "LIKE_UPLOAD_REQUEST";
export const LIKE_UPLOAD_SUCCESS = "LIKE_UPLOAD_SUCCESS";
export const LIKE_UPLOAD_FAIL = "LIKE_UPLOAD_FAIL";

export const CHECK_IF_LIKED_REQUEST = "CHECK_IF_LIKED_REQUEST";
export const CHECK_IF_LIKED_SUCCESS = "CHECK_IF_LIKED_SUCCESS";
export const CHECK_IF_LIKED_FAIL = "CHECK_IF_LIKED_FAIL";
