export const SAVE_UPLOAD_REQUEST = "SAVE_UPLOAD_REQUEST";
export const SAVE_UPLOAD_SUCCESS = "SAVE_UPLOAD_SUCCESS";
export const SAVE_UPLOAD_FAIL = "SAVE_UPLOAD_FAIL";

export const CHECK_IF_SAVED_REQUEST = "CHECK_IF_SAVED_REQUEST";
export const CHECK_IF_SAVED_SUCCESS = "CHECK_IF_SAVED_SUCCESS";
export const CHECK_IF_SAVED_FAIL = "CHECK_IF_SAVED_FAIL";

export const GET_USER_SAVED_UPLOADS_REQUEST = "GET_USER_SAVED_UPLOADS_REQUEST";
export const GET_USER_SAVED_UPLOADS_SUCCESS = "GET_USER_SAVED_UPLOADS_SUCCESS";
export const GET_USER_SAVED_UPLOADS_FAIL = "GET_USER_SAVED_UPLOADS_FAIL";
export const GET_USER_SAVED_UPLOADS_RESET = "GET_USER_SAVED_UPLOADS_RESET";
