export const SAVE_UPLOAD_REQUEST = "SAVE_UPLOAD_REQUEST";
export const SAVE_UPLOAD_SUCCESS = "SAVE_UPLOAD_SUCCESS";
export const SAVE_UPLOAD_FAIL = "SAVE_UPLOAD_FAIL";

export const CHECK_IF_SAVED_REQUEST = "CHECK_IF_SAVED_REQUEST";
export const CHECK_IF_SAVED_SUCCESS = "CHECK_IF_SAVED_SUCCESS";
export const CHECK_IF_SAVED_FAIL = "CHECK_IF_SAVED_FAIL";
