export const UPLOAD_POST_REQUEST = "UPLOAD_POST_REQUEST";
export const UPLOAD_POST_SUCCESS = "UPLOAD_POST_SUCCESS";
export const UPLOAD_POST_FAIL = "UPLOAD_POST_FAIL";

export const GET_ALL_USER_UPLOADS_REQUEST = "GET_All_USER_UPLOADS_REQUEST";
export const GET_ALL_USER_UPLOADS_SUCCESS = "GET_All_USER_UPLOADS_SUCCESS";
export const GET_ALL_USER_UPLOADS_FAIL = "GET_All_USER_UPLOADS_FAIL";

//get loggedIn users following posts
export const GET_LOGGED_IN_USER_FOLLOWING_POSTS_REQUEST =
  "GET_LOGGED_IN_USER_FOLLOWING_POSTS_REQUEST";
export const GET_LOGGED_IN_USER_FOLLOWING_POSTS_SUCCESS =
  "GET_LOGGED_IN_USER_FOLLOWING_POSTS_SUCCESS";
export const GET_LOGGED_IN_USER_FOLLOWING_POSTS_FAIL = "GET_LOGGED_IN_USER_FOLLOWING_POSTS_FAIL";

export const GET_UPLOAD_DETAILS_REQUEST = "GET_UPLOAD_DETAILS_REQUEST";
export const GET_UPLOAD_DETAILS_SUCCESS = "GET_UPLOAD_DETAILS_SUCCESS";
export const GET_UPLOAD_DETAILS_FAIL = "GET_UPLOAD_DETAILS_FAIL";

export const UPDATE_UPLOAD_REQUEST = "UPDATE_UPLOAD_REQUEST";
export const UPDATE_UPLOAD_SUCCESS = "UPDATE_UPLOAD_SUCCESS";
export const UPDATE_UPLOAD_FAIL = "UPDATE_UPLOAD_FAIL";
