export const UPLOAD_POST_REQUEST = "UPLOAD_POST_REQUEST";
export const UPLOAD_POST_SUCCESS = "UPLOAD_POST_SUCCESS";
export const UPLOAD_POST_FAIL = "UPLOAD_POST_FAIL";

export const GET_ALL_USER_UPLOADS_REQUEST = "GET_All_USER_UPLOADS_REQUEST";
export const GET_ALL_USER_UPLOADS_SUCCESS = "GET_All_USER_UPLOADS_SUCCESS";
export const GET_ALL_USER_UPLOADS_FAIL = "GET_All_USER_UPLOADS_FAIL";
