//login
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

//logout
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";

//register
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

//get login user details
export const LOGGED_IN_USER_DETAILS_REQUEST = "LOGGED_IN_USER_DETAILS_REQUEST";
export const LOGGED_IN_USER_DETAILS_SUCCESS = "LOGGED_IN_USER_DETAILS_SUCCESS";
export const LOGGED_IN_USER_DETAILS_FAIL = "LOGGED_IN_USER_DETAILS_FAIL";
export const LOGGED_IN_USER_DETAILS_RESET = "LOGGED_IN_USER_DETAILS_RESET";

//get a specific user
export const ANY_USER_DETAILS_REQUEST = "ANY_USER_DETAILS_REQUEST";
export const ANY_USER_DETAILS_SUCCESS = "ANY_USER_DETAILS_SUCCESS";
export const ANY_USER_DETAILS_FAIL = "ANY_USER_DETAILS_FAIL";

//user updates profile picture
export const USER_UPDATE_PROFILE_PICTURE_REQUEST = "USER_UPDATE_PROFILE_PICTURE_REQUEST";
export const USER_UPDATE_PROFILE_PICTURE_SUCCESS = "USER_UPDATE_PROFILE_PICTURE_SUCCESS";
export const USER_UPDATE_PROFILE_PICTURE_FAIL = "USER_UPDATE_PROFILE_PICTURE_FAIL";

//user updates names
export const USER_UPDATE_NAMES_REQUEST = "USER_UPDATE_NAMES_REQUEST";
export const USER_UPDATE_NAMES_SUCCESS = "USER_UPDATE_NAMES_SUCCESS";
export const USER_UPDATE_NAMES_FAIL = "USER_UPDATE_NAMES_FAIL";

//user updates names
export const USER_GET_PROFILE_PIC_REQUEST = "USER_GET_PROFILE_PIC_REQUEST";
export const USER_GET_PROFILE_PIC_SUCCESS = "USER_GET_PROFILE_PIC_SUCCESS";
export const USER_GET_PROFILE_PIC_FAIL = "USER_GET_PROFILE_PIC_FAIL";
export const USER_GET_PROFILE_PIC_RESET = "USER_GET_PROFILE_PIC_RESET";
//user updates names
export const USER_REMOVE_PROFILE_PIC_REQUEST = "USER_REMOVE_PROFILE_PIC_REQUEST";
export const USER_REMOVE_PROFILE_PIC_SUCCESS = "USER_REMOVE_PROFILE_PIC_SUCCESS";
export const USER_REMOVE_PROFILE_PIC_FAIL = "USER_REMOVE_PROFILE_PIC_FAIL";
export const USER_REMOVE_PROFILE_PIC_RESET = "USER_REMOVE_PROFILE_PIC_RESET";
